# Generated by Django 5.0.6 on 2024-05-24 08:50

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_like_sender_likecomment_like_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
