# Generated by Django 5.0.6 on 2024-05-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to='chats.chatgroup'),
        ),
    ]
